### ISSUE TITLE
Incorrect I/O being used

### ISSUE THREAD

**Issue by Anvadya** [Anvadya/Pipelined-Processor#3]
The files for the various pipelined stages are not using the IF/Of, OF/Ex and other registers as inputs and outputs.

**Comment by jainl28patel** [comment]
Where is it happening ? in our design or someone's code ??

**Comment by Anvadya** [comment]
In everyone's code. The units have a list of inputs and outputs, like separate input for PC, Instruction and all. The stages of pipeline must take their input and output as the pipeline registers.
